apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolldice
  namespace: default
  labels:
    app: rolldice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rolldice
  template:
    metadata:
      labels:
        app: rolldice
    spec:
      containers:
      - name: api
        image: docker.io/library/otel-go-diiage:1
        env:
          - name: OTEL_SERVICE_NAME
            value: rolldice
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://otel-collector:4317
#          - name: OTEL_LOG_LEVEL
#            value: debug
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: rolldice
spec:
  selector:
    app: rolldice
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
